version: '2'
services:
    match:
        environment:
            ELASTICSEARCH_URL: "http://match-elasticsearch:9200"
            ELASTICSEARCH_INDEX: "images"
            ELASTICSEARCH_DOC_TYPE: "images"
            PORT: 80

        build: .
        container_name: match
        expose:
            - "80"
        networks:
            - matchnet

    elasticsearch:
        image: elasticsearch
        container_name: match-elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - matchnet

networks:
    matchnet:

