version: '2'
services:
  match:
    image: pavlov/match:latest
    ports:
    - 8888:8888
    environment:
    - PORT=8888
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "env", "PORT=8888", "python", "/server.py"]
    links:
    - elasticsearch
  elasticsearch:
    image: elasticsearch
    ports:
    - 9200:9200
